name: figma-plugin-backend
services:
  - name: api
    source_dir: /backend
    github:
      repo: YOUR_USERNAME/YOUR_REPO_NAME
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "8080"
